plugins { id 'com.android.application' }

android {
    namespace 'com.jarvis.homemultitool'
    compileSdk 35
    signingConfigs {
        jarvisRelease {
            storeFile file('../jarvis-release.jks')
            storePassword 'jarvis-release-2026'
            keyAlias 'jarvis'
            keyPassword 'jarvis-release-2026'
        }
    }
    defaultConfig {
        applicationId 'com.jarvis.homemultitool'
        minSdk 26
        targetSdk 35
        versionCode 17
        versionName '5.13.0-professional-hud'
    }
    buildTypes {
        release {
            signingConfig signingConfigs.jarvisRelease
            minifyEnabled false
        }
        debug {
            signingConfig signingConfigs.jarvisRelease
        }
    }
}
