package com.jarvis.homemultitool;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.speech.*;import android.view.WindowManager;import java.util.*;

/** Reliable foreground wake-word bridge. It releases the microphone before opening MainActivity. */
public class JarvisWakeWordService extends Service {
 private static final String CHANNEL="jarvis_wake";private static final int NOTIFY=71;private SpeechRecognizer recognizer;private Intent intent;private Handler handler;private boolean running,listening,triggered;
 @Override public void onCreate(){super.onCreate();handler=new Handler(getMainLooper());createChannel();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){stopSelf();return;}if(!startForegroundCompat())return;if(!SpeechRecognizer.isRecognitionAvailable(this)){stopSelf();return;}intent=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM).putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ru-RU").putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,5).putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true).putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE,false);running=true;createRecognizer();startListening(400);}
 private boolean startForegroundCompat(){try{Intent open=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent pi=PendingIntent.getActivity(this,72,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setSmallIcon(android.R.drawable.ic_btn_speak_now).setContentTitle("JARVIS • фоновый вызов").setContentText("Ожидание фразы «Джарвис»").setContentIntent(pi).setOngoing(true).setCategory(Notification.CATEGORY_SERVICE);if(Build.VERSION.SDK_INT>=29)startForeground(NOTIFY,b.build(),android.content.pm.ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);else startForeground(NOTIFY,b.build());return true;}catch(Throwable e){stopSelf();return false;}}
 private void createRecognizer(){try{if(recognizer!=null)recognizer.destroy();recognizer=(Build.VERSION.SDK_INT>=31&&SpeechRecognizer.isOnDeviceRecognitionAvailable(this))?SpeechRecognizer.createOnDeviceSpeechRecognizer(this):SpeechRecognizer.createSpeechRecognizer(this);if(recognizer!=null)recognizer.setRecognitionListener(listener);}catch(Throwable e){recognizer=null;}}
 private final RecognitionListener listener=new RecognitionListener(){public void onReadyForSpeech(Bundle b){listening=true;}public void onBeginningOfSpeech(){listening=true;}public void onRmsChanged(float v){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){listening=false;}public void onError(int e){listening=false;rearm(700);}public void onPartialResults(Bundle b){check(b);}public void onResults(Bundle b){check(b);if(!triggered){listening=false;startListening(350);}}public void onEvent(int a,Bundle b){}};
 private void check(Bundle b){if(triggered||b==null)return;ArrayList<String> rs=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(rs==null)return;for(String s:rs){if(s==null)continue;String x=s.toLowerCase(new Locale("ru")).trim();if(x.matches(".*\\bджарвис(у|а|ом)?\\b.*")){triggered=true;String q=x.replaceAll("(?i)\\bджарвис(у|а|ом)?\\b"," ").replaceAll("\\s+"," ").trim();launch(q);return;}}}
 private void launch(String q){try{if(recognizer!=null){recognizer.cancel();recognizer.destroy();recognizer=null;}running=false;Intent i=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);i.putExtra("WAKE_WORD",true);if(!q.isEmpty())i.putExtra("WAKE_QUERY",q);i.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);startActivity(i);}catch(Throwable ignored){}handler.postDelayed(this::stopSelf,250);}
 private void rearm(long delay){if(!running||triggered)return;handler.postDelayed(()->{if(!running||triggered)return;createRecognizer();startListening(100);},delay);}
 private void startListening(long delay){if(!running||triggered)return;handler.postDelayed(()->{if(!running||triggered||recognizer==null||listening)return;try{recognizer.cancel();recognizer.startListening(intent);}catch(Throwable e){rearm(1000);}},delay);}
 @Override public int onStartCommand(Intent i,int flags,int id){return START_STICKY;}
 @Override public void onDestroy(){running=false;if(handler!=null)handler.removeCallbacksAndMessages(null);if(recognizer!=null)try{recognizer.destroy();}catch(Throwable ignored){}super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"JARVIS • фоновый вызов",NotificationManager.IMPORTANCE_LOW);c.setDescription("Фоновое ожидание команды «Джарвис»");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
}
