package com.jarvis.homemultitool;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.speech.*;import android.view.WindowManager;import java.util.*;

/** Background wake bridge. Android may stop microphone services on some OEMs; the service restarts recognition windows when permitted. */
public class JarvisWakeWordService extends Service{
 private static final String CHANNEL="jarvis_wake";private SpeechRecognizer recognizer;private Intent intent;private boolean running,triggered;private Handler h;private Runnable restart;
 @Override public void onCreate(){super.onCreate();h=new Handler(Looper.getMainLooper());createChannel();startForegroundCompat();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){stopSelf();return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){stopSelf();return;}intent=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM).putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ru-RU").putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,5).putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true).putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE,true);try{recognizer=(Build.VERSION.SDK_INT>=31&&SpeechRecognizer.isOnDeviceRecognitionAvailable(this))?SpeechRecognizer.createOnDeviceSpeechRecognizer(this):SpeechRecognizer.createSpeechRecognizer(this);}catch(Throwable e){recognizer=null;}if(recognizer==null){stopSelf();return;}recognizer.setRecognitionListener(listener);running=true;startListening();}
 private void startForegroundCompat(){Notification n=new Notification.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.ic_btn_speak_now).setContentTitle("JARVIS • голосовой вызов").setContentText("Ожидание фразы «Джарвис»").setOngoing(true).setCategory(Notification.CATEGORY_SERVICE).build();if(Build.VERSION.SDK_INT>=29)startForeground(71,n,android.content.pm.ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);else startForeground(71,n);}
 private final RecognitionListener listener=new RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float v){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){scheduleRestart(700);}public void onPartialResults(Bundle b){check(b);}public void onResults(Bundle b){check(b);scheduleRestart(450);}public void onEvent(int a,Bundle b){}};
 private void check(Bundle b){if(triggered)return;ArrayList<String> r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(r==null)return;for(String s:r){String x=s.toLowerCase(new Locale("ru")).trim();if(x.contains("джарвис")||x.contains("джарвису")){triggered=true;String q=x.replaceAll("(?i)джарвису?"," ").replaceAll("^[,.:;\\-]+","").trim();launch(q);return;}}}
 private void launch(String q){try{if(recognizer!=null)recognizer.cancel();Intent i=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT|Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);i.putExtra("WAKE_WORD",true);if(!q.isEmpty())i.putExtra("WAKE_QUERY",q);i.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);startActivity(i);}catch(Throwable ignored){}h.postDelayed(()->{triggered=false;if(running)startListening();},1800);}
 private void scheduleRestart(long ms){if(!running)return;if(restart!=null)h.removeCallbacks(restart);restart=()->startListening();h.postDelayed(restart,ms);}
 private void startListening(){if(!running||recognizer==null)return;try{recognizer.cancel();}catch(Throwable ignored){}try{recognizer.startListening(intent);}catch(Throwable e){scheduleRestart(1000);}}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"JARVIS • голосовой вызов",NotificationManager.IMPORTANCE_LOW);c.setDescription("Фоновое ожидание команды «Джарвис»");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
 @Override public int onStartCommand(Intent i,int flags,int id){return START_STICKY;}
 @Override public void onDestroy(){running=false;if(restart!=null)h.removeCallbacks(restart);if(recognizer!=null)try{recognizer.destroy();}catch(Throwable ignored){}super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
}
