package com.jarvis.homemultitool;

import android.Manifest;import android.app.Activity;import android.app.role.RoleManager;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;

public class SettingsActivity extends Activity{
 private static final int BG=Color.rgb(2,6,10),SUR=Color.rgb(5,16,27),CYAN=Color.rgb(91,224,255),WHITE=Color.rgb(242,247,255),MUTED=Color.rgb(126,157,184),GREEN=Color.rgb(71,232,177),RED=Color.rgb(255,102,116);private static final int REQ=51;private TextView roleState,wakeState,micState;
 private int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}private TextView tv(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextColor(WHITE);v.setTextSize(z);return v;}private GradientDrawable box(int st,int fill,float r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));if(st!=0)g.setStroke(dp(1),st);return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
 private TextView button(String s,View.OnClickListener c){TextView v=tv(s,14);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setBackground(box(0xFF155078,SUR,25));v.setOnClickListener(c);return v;}
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();refresh();}
 private void build(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(10),dp(16),dp(24));
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",38);back.setGravity(Gravity.CENTER);back.setTextColor(CYAN);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(52),dp(52)));TextView title=tv("JARVIS",25);title.setTextColor(CYAN);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setLetterSpacing(.14f);title.setGravity(Gravity.CENTER);head.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(head);TextView sub=tv("СИСТЕМА • ГОЛОС • ВЫЗОВ • ПРИВАТНОСТЬ",11);sub.setTextColor(MUTED);sub.setTypeface(Typeface.DEFAULT,Typeface.BOLD);sub.setLetterSpacing(.1f);root.addView(sub,lp(-1,30,0,4,0,12));
  section(root,"СИСТЕМНЫЙ АССИСТЕНТ");LinearLayout card=card();row(card,"JARVIS как помощник Android", "Основной голосовой помощник системы",v->requestRole(),roleState=newState());root.addView(card,lp(-1,-2,0,0,0,12));
  section(root,"ВЫЗОВ «ДЖАРВИС»");LinearLayout wake=card();row(wake,"Фоновое ожидание фразы", "Фоновый микрофон JARVIS с постоянным уведомлением",v->toggleWake(),wakeState=newState());TextView note=tv("Для постоянного фонового микрофона Android требует разрешение на микрофон и постоянное уведомление. На некоторых оболочках автозапуск также нужно разрешить вручную.",12);note.setTextColor(MUTED);note.setLineSpacing(0,1.15f);wake.addView(note,lp(-1,-2,0,8,0,4));root.addView(wake,lp(-1,-2,0,0,0,12));
  section(root,"МИКРОФОН");LinearLayout mc=card();LinearLayout mr=new LinearLayout(this);mr.setGravity(Gravity.CENTER_VERTICAL);TextView mt=tv("Разрешение микрофона",15);mt.setTypeface(Typeface.DEFAULT,Typeface.BOLD);mr.addView(mt,new LinearLayout.LayoutParams(0,48,1));micState=newState();mr.addView(micState);mc.addView(mr);TextView mb=button("РАЗРЕШИТЬ МИКРОФОН",v->requestMic());mc.addView(mb,lp(-1,50,0,8,0,0));root.addView(mc,lp(-1,-2,0,0,0,12));
  section(root,"РЕЧЬ");root.addView(button("НАСТРОЙКИ СИНТЕЗА РЕЧИ ANDROID",v->open("com.android.settings.TTS_SETTINGS")),lp(-1,50,0,0,0,8));root.addView(button("НАСТРОЙКИ ГОЛОСОВОГО ВВОДА ANDROID",v->open(Settings.ACTION_VOICE_INPUT_SETTINGS)),lp(-1,50,0,0,0,12));
  section(root,"РАЗРЕШЕНИЯ И ДИАГНОСТИКА");root.addView(button("РАЗРЕШЕНИЯ ПРИЛОЖЕНИЯ",v->openAppSettings()),lp(-1,50,0,0,0,8));root.addView(button("ТОЧНЫЕ БУДИЛЬНИКИ И НАПОМИНАНИЯ",v->open(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM)),lp(-1,50,0,0,0,8));TextView p=tv("JARVIS не должен сообщать об успешном действии, пока Android не подтвердил его выполнение. Таймеры используют системный таймер Clock, а при отсутствии подходящего приложения — AlarmManager как резервный механизм.",12);p.setTextColor(MUTED);p.setLineSpacing(0,1.15f);root.addView(p,lp(-1,-2,0,8,0,0));sc.addView(root);setContentView(sc);}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(box(0xFF155078,SUR,24));return c;}
 private void row(LinearLayout c,String title,String desc,View.OnClickListener click,TextView state){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);TextView t=tv(title,15);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);text.addView(t);TextView d=tv(desc,12);d.setTextColor(MUTED);text.addView(d,lp(-1,-2,0,3,0,0));r.addView(text,new LinearLayout.LayoutParams(0,54,1));r.addView(state,lp(90,32,10,0,0,0));c.addView(r);TextView b=button("ОТКРЫТЬ / ИЗМЕНИТЬ",click);c.addView(b,lp(-1,48,0,10,0,0));}
 private TextView newState(){TextView v=tv("—",11);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private void section(LinearLayout r,String s){TextView v=tv(s,11);v.setTextColor(CYAN);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setLetterSpacing(.12f);r.addView(v,lp(-1,28,2,6,0,3));}
 private void requestRole(){if(Build.VERSION.SDK_INT>=29){try{RoleManager rm=getSystemService(RoleManager.class);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_ASSISTANT)&&!rm.isRoleHeld(RoleManager.ROLE_ASSISTANT)){startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_ASSISTANT),41);return;}}catch(Throwable ignored){}}open(Settings.ACTION_VOICE_INPUT_SETTINGS);}
 private void requestMic(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ);else refresh();}
 private void toggleWake(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ);getSharedPreferences("jarvis",0).edit().putBoolean("wake_pending",true).apply();return;}boolean on=getSharedPreferences("jarvis",0).getBoolean("wake_enabled",false);getSharedPreferences("jarvis",0).edit().putBoolean("wake_enabled",!on).apply();Intent i=new Intent(this,JarvisWakeWordService.class);try{if(!on){if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}else stopService(i);}catch(Throwable ignored){}refresh();}
 private void refresh(){boolean role=JarvisVoiceInteractionService.isActive(this);roleState.setText(role?"АКТИВЕН":"НЕ ВЫБРАН");roleState.setTextColor(role?GREEN:MUTED);boolean wake=getSharedPreferences("jarvis",0).getBoolean("wake_enabled",false);wakeState.setText(wake?"ВКЛЮЧЕН":"ВЫКЛЮЧЕН");wakeState.setTextColor(wake?GREEN:MUTED);boolean mic=Build.VERSION.SDK_INT<23||checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED;micState.setText(mic?"РАЗРЕШЁН":"НЕТ");micState.setTextColor(mic?GREEN:RED);}
 private void open(String action){try{startActivity(new Intent(action));}catch(Throwable e){startActivity(new Intent(Settings.ACTION_SETTINGS));}}private void openAppSettings(){Intent i=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);i.setData(android.net.Uri.parse("package:"+getPackageName()));startActivity(i);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED&&getSharedPreferences("jarvis",0).getBoolean("wake_pending",false)){getSharedPreferences("jarvis",0).edit().putBoolean("wake_pending",false).putBoolean("wake_enabled",true).apply();try{Intent i=new Intent(this,JarvisWakeWordService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Throwable ignored){}}refresh();}
 @Override protected void onResume(){super.onResume();if(roleState!=null)refresh();}
}
