package com.jarvis.homemultitool;

import android.Manifest;
import android.app.*;
import android.app.role.RoleManager;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.TextUtils;
import android.util.TypedValue;
import android.view.*;
import android.widget.*;

/** Stable, compact settings UI. Every action is either local or opens a concrete Android settings page. */
public class SettingsActivity extends Activity {
    private static final int BG=Color.rgb(2,6,11), PANEL=Color.rgb(7,16,26), CYAN=Color.rgb(91,220,255), BORDER=Color.rgb(27,96,139), WHITE=Color.rgb(242,247,255), MUTED=Color.rgb(126,151,174), GREEN=Color.rgb(70,226,174), RED=Color.rgb(255,103,119);
    private static final int REQ_MIC=51;
    private TextView roleState,wakeState,micState,voiceState; private JarvisVoiceManager voice;
    private int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    private TextView label(String s,float sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(WHITE);v.setTextSize(TypedValue.COMPLEX_UNIT_SP,sp);v.setIncludeFontPadding(false);v.setGravity(Gravity.CENTER_VERTICAL);v.setBreakStrategy(android.text.Layout.BREAK_STRATEGY_SIMPLE);return v;}
    private GradientDrawable bg(int stroke,int fill,float radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));if(stroke>0)g.setStroke(dp(1),stroke);return g;}
    private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    private TextView button(String s,View.OnClickListener click){TextView v=label(s,12);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setSingleLine(true);v.setEllipsize(TextUtils.TruncateAt.END);v.setPadding(dp(10),0,dp(10),0);v.setBackground(bg(BORDER,0xF0091824,16));v.setOnClickListener(click);return v;}
    private TextView icon(String s,View.OnClickListener click){TextView v=button(s,20);v.setTextColor(CYAN);return v;}
    @Override protected void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);if(Build.VERSION.SDK_INT>=29){getWindow().setStatusBarContrastEnforced(false);getWindow().setNavigationBarContrastEnforced(false);}getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);try{voice=new JarvisVoiceManager(this);voice.init(()->new Handler(Looper.getMainLooper()).post(this::refresh));}catch(Throwable ignored){}build();}
    private void build(){
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(12),dp(18),dp(30));scroll.addView(root,new ScrollView.LayoutParams(-1,-1));
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.addView(icon("‹",v->finish()),new LinearLayout.LayoutParams(dp(48),dp(48)));TextView title=label("J A R V I S",22);title.setTextColor(CYAN);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setGravity(Gravity.CENTER);title.setLetterSpacing(.18f);header.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));header.addView(icon("⚙",v->safeOpen(new Intent(Settings.ACTION_SETTINGS),new Intent(Settings.ACTION_SETTINGS))),new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(header);
        TextView sub=label("СИСТЕМА  •  ГОЛОС  •  ВЫЗОВ  •  ПРИВАТНОСТЬ",9);sub.setTextColor(MUTED);sub.setTypeface(Typeface.DEFAULT,Typeface.BOLD);sub.setLetterSpacing(.045f);root.addView(sub,lp(-1,22,2,7,0,8));
        section(root,"СИСТЕМНЫЙ АССИСТЕНТ");addStatusCard(root,"JARVIS как помощник Android","Назначить JARVIS системным помощником для вызова поверх других приложений.",roleState=state("—"),"ОТКРЫТЬ НАСТРОЙКУ",v->requestRole());
        section(root,"АКТИВАЦИЯ ГОЛОСОМ");addStatusCard(root,"«Привет, Джарвис»","Фоновое ожидание работает через foreground microphone service. Android может ограничивать фоновые микрофоны — состояние показывается честно.",wakeState=state("—"),"ВКЛЮЧИТЬ / ВЫКЛЮЧИТЬ",v->toggleWake());addAction(root,"НАСТРОИТЬ БАТАРЕЮ",v->openBattery());
        section(root,"МИКРОФОН");addStatusCard(root,"Доступ к микрофону","Нужен для голосовых команд и фонового вызова.",micState=state("—"),"ОТКРЫТЬ РАЗРЕШЕНИЯ",v->requestMic());
        section(root,"ГОЛОС JARVIS");addVoiceCard(root);
        section(root,"СИСТЕМНЫЕ РАЗДЕЛЫ");addAction(root,"ГОЛОСОВОЙ ВВОД",v->safeOpen(new Intent(Settings.ACTION_VOICE_INPUT_SETTINGS),new Intent(Settings.ACTION_SETTINGS)));addAction(root,"УВЕДОМЛЕНИЯ JARVIS",v->safeOpen(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()).setData(Uri.parse("package:"+getPackageName())),new Intent(Settings.ACTION_SETTINGS)));addAction(root,"РАЗРЕШЕНИЯ JARVIS",v->safeOpen(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())),new Intent(Settings.ACTION_APPLICATION_SETTINGS)));if(Build.VERSION.SDK_INT>=31)addAction(root,"ТОЧНЫЕ БУДИЛЬНИКИ",v->safeOpen(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM,Uri.parse("package:"+getPackageName())),new Intent(Settings.ACTION_SETTINGS)));addAction(root,"ОПТИМИЗАЦИЯ БАТАРЕИ",v->openBattery());addAction(root,"ЭКРАН",v->safeOpen(new Intent(Settings.ACTION_DISPLAY_SETTINGS),new Intent(Settings.ACTION_SETTINGS)));addAction(root,"WI-FI",v->safeOpen(new Intent(Settings.ACTION_WIFI_SETTINGS),new Intent(Settings.ACTION_SETTINGS)));addAction(root,"BLUETOOTH",v->safeOpen(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS),new Intent(Settings.ACTION_SETTINGS)));
        TextView foot=label("JARVIS не рисует фальшивые переключатели: состояние отображается из Android, а системные кнопки ведут в соответствующий раздел ОС.",10);foot.setTextColor(MUTED);foot.setLineSpacing(0,1.12f);root.addView(foot,lp(-1,-2,2,12,0,0));setContentView(scroll);refresh();
    }
    private void addStatusCard(LinearLayout root,String title,String desc,TextView state,String action,View.OnClickListener click){LinearLayout c=card();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView t=label(title,16);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(t,new LinearLayout.LayoutParams(0,dp(28),1));top.addView(state,new LinearLayout.LayoutParams(dp(92),dp(28)));c.addView(top);TextView d=label(desc,11);d.setTextColor(MUTED);d.setMaxLines(4);d.setEllipsize(TextUtils.TruncateAt.END);c.addView(d,lp(-1,-2,0,6,0,0));c.addView(button(action,click),lp(-1,dp(48),0,12,0,0));root.addView(c,lp(-1,-2,0,0,0,10));}
    private void addVoiceCard(LinearLayout root){LinearLayout c=card();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView t=label("Профиль ответа",16);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(t,new LinearLayout.LayoutParams(0,dp(28),1));voiceState=state("—");top.addView(voiceState,new LinearLayout.LayoutParams(dp(92),dp(28)));c.addView(top);TextView d=label("Используется реальный русский TTS-движок телефона. JARVIS выбирает установленный мужской или женский голос; синтетический голос не подменяется записанными фразами.",11);d.setTextColor(MUTED);d.setMaxLines(4);c.addView(d,lp(-1,-2,0,6,0,0));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView male=button("МУЖСКОЙ",v->{voice.setGender(JarvisVoiceManager.MALE);voice.speak("Мужской профиль активирован.",null);refresh();});TextView female=button("ЖЕНСКИЙ",v->{voice.setGender(JarvisVoiceManager.FEMALE);voice.speak("Женский профиль активирован.",null);refresh();});row.addView(male,new LinearLayout.LayoutParams(0,dp(48),1));row.addView(female,lp(0,48,8,0,0,0));c.addView(row,lp(-1,dp(48),0,12,0,0));c.addView(button("АВТОМАТИЧЕСКИЙ ПРОФИЛЬ",v->{voice.setGender(JarvisVoiceManager.AUTO);refresh();}),lp(-1,48,0,8,0,0));c.addView(button("НАСТРОЙКИ СИНТЕЗА РЕЧИ",v->openTtsSettings()),lp(-1,48,0,8,0,0));root.addView(c,lp(-1,-2,0,0,0,10));}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(bg(BORDER,0xF007141F,22));return c;}
    private TextView state(String s){TextView v=label(s,9);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setSingleLine(true);v.setTextColor(MUTED);return v;}
    private void addAction(LinearLayout root,String s,View.OnClickListener c){root.addView(button(s,c),lp(-1,dp(48),0,0,0,8));}
    private void section(LinearLayout root,String s){TextView v=label(s,9);v.setTextColor(CYAN);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setLetterSpacing(.08f);root.addView(v,lp(-1,dp(20),2,5,0,4));}
    private void requestRole(){if(Build.VERSION.SDK_INT>=29){try{RoleManager rm=getSystemService(RoleManager.class);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_ASSISTANT)){if(!rm.isRoleHeld(RoleManager.ROLE_ASSISTANT)){startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_ASSISTANT),41);}else refresh();return;}}catch(Throwable ignored){}}safeOpen(new Intent(Settings.ACTION_VOICE_INPUT_SETTINGS),new Intent(Settings.ACTION_SETTINGS));}
    private void requestMic(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);else safeOpen(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())),new Intent(Settings.ACTION_APPLICATION_SETTINGS));}
    private void toggleWake(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){getSharedPreferences("jarvis",0).edit().putBoolean("wake_pending",true).apply();requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}boolean on=getSharedPreferences("jarvis",0).getBoolean("wake_enabled",false);getSharedPreferences("jarvis",0).edit().putBoolean("wake_enabled",!on).apply();try{Intent i=new Intent(this,JarvisWakeWordService.class);if(!on){if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}else stopService(i);}catch(Throwable e){getSharedPreferences("jarvis",0).edit().putBoolean("wake_enabled",false).apply();Toast.makeText(this,"Android не разрешил фоновый микрофон. Проверьте разрешения и батарею.",Toast.LENGTH_LONG).show();}refresh();}
    private void openBattery(){safeOpen(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())),new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}
    private void openTtsSettings(){safeOpen(new Intent("android.settings.TTS_SETTINGS"),new Intent(Settings.ACTION_SETTINGS));}
    private void safeOpen(Intent primary,Intent fallback){try{if(primary!=null&&primary.resolveActivity(getPackageManager())!=null){startActivity(primary);return;}}catch(Throwable ignored){}try{if(fallback!=null&&fallback.resolveActivity(getPackageManager())!=null){startActivity(fallback);return;}startActivity(new Intent(Settings.ACTION_SETTINGS));}catch(Throwable ignored){}}
    private void refresh(){if(roleState==null)return;boolean role=JarvisVoiceInteractionService.isActive(this);roleState.setText(role?"АКТИВЕН":"НЕ ВЫБРАН");roleState.setTextColor(role?GREEN:MUTED);boolean wake=getSharedPreferences("jarvis",0).getBoolean("wake_enabled",false);wakeState.setText(wake?"ВКЛЮЧЕН":"ВЫКЛЮЧЕН");wakeState.setTextColor(wake?GREEN:MUTED);boolean mic=Build.VERSION.SDK_INT<23||checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED;micState.setText(mic?"РАЗРЕШЁН":"НЕТ");micState.setTextColor(mic?GREEN:RED);String g=voice==null?JarvisVoiceManager.AUTO:voice.getGender();voiceState.setText(JarvisVoiceManager.MALE.equals(g)?"МУЖСКОЙ":JarvisVoiceManager.FEMALE.equals(g)?"ЖЕНСКИЙ":"АВТО");voiceState.setTextColor(CYAN);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_MIC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED&&getSharedPreferences("jarvis",0).getBoolean("wake_pending",false)){getSharedPreferences("jarvis",0).edit().putBoolean("wake_pending",false).putBoolean("wake_enabled",true).apply();try{Intent i=new Intent(this,JarvisWakeWordService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Throwable ignored){}}refresh();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){if(voice!=null)voice.shutdown();super.onDestroy();}
}
